### ISSUE TITLE
Spectral Capsule Networks

### ISSUE THREAD

**Issue by Taha-Bahadori** [aisummary/awesome-capsule-networks#4]
Hi Sebastian,

I would love to know your opinion about this work on CapNets:
https://openreview.net/forum?id=ByVJlqR8G

Best,
Taha

**Comment by sekwiatkowski** [comment]
Hi Taha,

medical applications and faster convergence are definitely awesome! I'm assuming that the paper is currently being reviewed. Is that correct?

I'm thinking about opening a section for cutting edge papers that are under review.

Thanks,
Sebastian

**Comment by Taha-Bahadori** [comment]
Thanks for the comments.  

Yes, it is currently under review and the decision is due on March 9th.

Nice compilation, btw.

**Comment by sekwiatkowski** [comment]
I've added a section for papers under review and included your paper.

**Comment by Taha-Bahadori** [comment]
Thank you.  I will update you about the decision soon.

**Comment by sekwiatkowski** [comment]
I will close the the issue now. Feel free to reopen when there is a new development.

**Comment by sairaamVenkatraman** [comment]
@Taha-Bahadori  Is the code available?

**Comment by Taha-Bahadori** [comment]
@sairaamVenkatraman Unfortunately, I have to get a separate approval for publishing the source code and I have not done that yet.  But, it should be quite simple to implement if you already have a capsule network implemented.

**Comment by ashleylid** [comment]
Hi, I can't find the paper - is it still out there?

**Comment by Taha-Bahadori** [comment]
@kleinash It is here:
https://openreview.net/forum?id=HJuMvYPaM
